### ISSUE TITLE
Improve behaviour of cards receiving messages before they activate

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#14]
Cards pending activation should queue messages to be processed in-order, or via some reasonable semantic once active.

**Comment by cyril-sf** [comment]
This should be the case as the communication between the containing environment and the card through a service is made with `MessagePort.postMessage`.

Can you give more details so I can reproduce the issue?

**Comment by stefanpenner** [comment]
The scenario is: One card has a resource that fails to resolve, and another card sends it a message. This message is received but the card is essentially in an error state.

I can provide an example if needed.

**Comment by hjdivad** [comment]
``` js
card.appendTo(document.body);
card.render('something');
```

We should connect `xhr` and `data` first and connect everything else during activation.  This is all stuff to fixup in `conductor/card.js`
