### ISSUE TITLE
no ability to load a card that does not need to be bootstrapped

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#19]
The use cases are:

loading a remote, prebuilt card from a remote ( `skylight.io/card_v1.html` ) or local (`../test_card.html`) origin.

**Comment by lukemelia** [comment]
FYI, this is not a high priority for us right now.

**Comment by cyril-sf** [comment]
The `sandbox` attribute doesn't seem to be supported by Internet Explorer 8 and 9.

http://msdn.microsoft.com/en-us/hh563496.aspx

Which means that if we don't implement this, we are dropping the security argument for those browsers.

**Comment by stefanpenner** [comment]
Even without @Cyril-sf's example, this is actually somewhat of a priority. Cards with domains "driver cards" should be used sparingly but, I believe we cripple things without.

**Comment by hjdivad** [comment]
@stefanpenner say more.  What is a domain "driver card"?

**Comment by stefanpenner** [comment]
Sorry, in our meetings we used the term Kernel space drivers to describe the behaviour of cards with a domain.

**Comment by hjdivad** [comment]
This is now possible via the polyglot.

**Comment by stefanpenner** [comment]
woop
