### ISSUE TITLE
Allow bring-your-own loader

### ISSUE THREAD

**Issue by lukemelia** [tildeio/conductor.js#29]
Conductor includes an AMD loader (`define` and `requireModule`), but it would be nice to be able to use your own if your app already is using AMD.

**Comment by cyril-sf** [comment]
Agree. We want to provide an AMD and a browser build of conductor.

**Comment by cyril-sf** [comment]
@lukemelia You can now use your own loader. You will have to integrate several libraries in your build process (UUID, MessageChannel, Kamino, RSVP and Oasis).
