### ISSUE TITLE
card.promise is resolved before card.activate is executed

### ISSUE THREAD

**Issue by lukemelia** [tildeio/conductor.js#32]
The intention of the code in activateWhen is clearly to execute activate first. @stefanpenner suggests this is likely a bug in RSVP 1.0.

**Comment by hjdivad** [comment]
with a bit of luck upgrading to rsvp 2.0 will take care of it then. ^_^

**Comment by lukemelia** [comment]
Turns out I was trolling myself. I had a CardReference and not a Card. What I really wanted to be using was: `card.sandbox.activatePromise`. Maybe this API should be exposed on card itself?

**Comment by hjdivad** [comment]
@lukemelia what's the use case?

`card.sandbox.activatePromise` is resolved when the card is activated, but the containing environment can send messages to the card before that: they'll get queued.

**Comment by stefanpenner** [comment]
I believe part of the confusion was that the card reference has a thenable promise property, which we assumed was what we needed. After some debugging we realized the activatePromise property on the card's sandbox  was what we wanted to use.

**Comment by lukemelia** [comment]
@hjdivad the particular use case for this was we were testing a card that does oauth and simulating the moment when the oauth popup window posts a message back to its opener (the card). I imagine we are bypassing the queuing mechanism in this flow.

**Comment by stefanpenner** [comment]
@lukemelia ya i think you are correct, that being said, I remember not bypassing and having similar issues. I will see if I can reproduce.

**Comment by hjdivad** [comment]
@stefanpenner @lukemelia is this still an issue?
