### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rmanalan** [tildeio/conductor.js#37]
I just ran into this lib while browsing through RSVP.js. What's the status of this project? Is there a license?

I'd love to test this out with my project.

**Comment by christse** [comment]
This project is under active development, led by Tilde and supported by McGraw-Hill Education Labs (@mhelabs). It is MIT licensed. Yapp Labs is working with MHELabs to build a dashboard framework using this library: https://github.com/yapplabs/glazier

**Comment by rmanalan** [comment]
Great thanks! I'm with Atlassian. We're working on something very similar. You guys up for discussing? Opportunity to team up?

**Comment by lukemelia** [comment]
@rmanalan I'm leading the dev effort on Glazier at Yapp Labs and would love to discuss. Email me at luke@yapp.us.
