### ISSUE TITLE
optionally enable/disable height service

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#54]

**Comment by hjdivad** [comment]
@stefanpenner do you want to disable the autoupdate?

`this.consumers.height.autoUpdate = false`

**Comment by stefanpenner** [comment]
it would be nice to also disable it from the containing environment, rather then on a per card basis.

**Comment by hjdivad** [comment]
@stefanpenner confirm.  You can technically do this by modifying `Conductor.capabilities` but I'm not entirely sure we want that to be the API.

**Comment by hjdivad** [comment]
``` js
Conductor.capabilities = [
  'xhr', 'metadata', 'render', 'data', 'lifecycle', 'height',
  'nestedWiretapping'
];
```

is the default

**Comment by stefanpenner** [comment]
seems strange to allow a card to resize itself if the container wants to disallow it

**Comment by hjdivad** [comment]
@stefanpenner not following; if the capability is removed, the card is not allowed to resize itself.

**Comment by stefanpenner** [comment]
good point

**Comment by cyril-sf** [comment]
@hjdivad we will still need to make that service optional when enabling web workers in Conductor.js

**Comment by hjdivad** [comment]
@Cyril-sf IIRC the consumer will no-op in a web worker
