### ISSUE TITLE
document custom conductor.js.html build

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#68]
likely improve/extract the following from glazier

https://github.com/yapplabs/glazier/blob/master/configurations/concat.js#L12-L18
https://github.com/yapplabs/glazier/blob/master/Gruntfile.js#L37-L43
https://github.com/yapplabs/glazier/tree/master/vendor/conductor

**Comment by hjdivad** [comment]
polyglot has gone away.

**Comment by cyril-sf** [comment]
RIP polyglot. You were loved.

**Comment by stefanpenner** [comment]
:+1:
