### ISSUE TITLE
cross-domain requests fail in IE

### ISSUE THREAD

**Issue by hjdivad** [tildeio/conductor.js#69]
IE uses XDomainRequest in an attempt to provide more jobs for the economy.  The xhr service needs to use XDomainRequest if it's available, and a standard XHR otherwise.
- http://msdn.microsoft.com/en-us/library/ie/cc288060(v=vs.85).aspx/html

cc @stefanpenner

**Comment by stefanpenner** [comment]
quickfix in one of our projects: https://github.com/mhelabs/mhe-metadata-js/commit/cdcb674014ed2d868659d19fb3f4d0a9c9ceb975 (fixed link, thanks @lukemelia )

Kinda seems like we should extract some of this work into an rsvp-ajax

**Comment by lukemelia** [comment]
@stefanpenner we killed that link. You might want to gist something.
