### ISSUE TITLE
Using browser back button causes issue loading iframes

### ISSUE THREAD

**Issue by raycohen** [tildeio/conductor.js#70]
Details and simplified example:

https://github.com/raycohen/iframe-back-issue

**Comment by lukemelia** [comment]
Suggested solution: Conductor (or maybe this is Oasis?) should set a unique iframe.name for each iframe it creates, perhaps with a combination of a counter and the current time:

``` javascript
var counter = 0;

// ...

iframe.name = sandbox.options.url + '?' + counter + new Date().getTime();
counter += 1;
```

**Comment by hjdivad** [comment]
:+1:  moaaaaaar hax

**Comment by cyril-sf** [comment]
@lukemelia any specific reason why you would want a timestamp?

**Comment by stefanpenner** [comment]
@Cyril-sf i think a per session guid of any kind is all the is needed.

**Comment by cyril-sf** [comment]
@stefanpenner sg

**Comment by cyril-sf** [comment]
@lukemelia @stefanpenner this commit bb7ff882e4871e3b08f9960c47d5ded646f5c54e should have fixed this issue. Let me know if this doesn't work.
