### ISSUE TITLE
Conductor.services is undefined when running through Tutorial

### ISSUE THREAD

**Issue by alvincrespo** [tildeio/conductor.js#90]
When trying to get the example playground running, I'm getting the following error:

`Uncaught TypeError: Cannot set property 'video' of undefined` on line 39 of playground-services.js

I've run the following commands:

`5912  cd ~/github/conductor.js/`
`5913  npm install`
`5914  grunt server`

**Comment by cyril-sf** [comment]
@alvincrespo The version of the tutorial in `master` isn't up to date.

I have used a version from the `tutorial` branch for MHE summit. I'm currently cleaning the code and plan on pushing it to master.

**Comment by cyril-sf** [comment]
This PR should have fixed everything https://github.com/tildeio/conductor.js/pull/92

**Comment by cyril-sf** [comment]
@alvincrespo Let me know if you still have a problem with that.
