### ISSUE TITLE
issues with real require

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/conductor.js#96]
https://github.com/tildeio/conductor.js/blob/master/vendor/loader.js#L1 

switching `requireModule` -> `require` across the board should solve this problem.

**Comment by cyril-sf** [comment]
@stefanpenner it's coming ( e444d6181993e464a47c9547a16a0c145b67b63d ) :-)

**Comment by stefanpenner** [comment]
also require force async only loading, so sync define followed by a require make requirejs unhappy.

**Comment by cyril-sf** [comment]
@stefanpenner RSVP.js doesn't play nicely with Almond.js on IE (https://github.com/tildeio/rsvp.js/issues/127). I'll have to revisit that commit.

**Comment by stefanpenner** [comment]
@Cyril-sf hmmm, can u provide me a fiddle or bin or something, I'll dig in once this evening.

**Comment by cyril-sf** [comment]
@stefanpenner will do. I'd also be happy to take a look at the issue later today.

The main issue seems that RSVP assumes that `this` is bound to the global object and this is not what Almond.js is doing.

**Comment by hjdivad** [comment]
so master has `require` now.  The provided loader will need to stay sync for the browser version.  We should still cleanup the amd version and make it easier to use (eg by letting people depend on `conductor/main` or `conductor/autorun` or something).

**Comment by hjdivad** [comment]
@stefanpenner please reopen if you still hit issues with the provided loader in the drop-in browser version.

**Comment by stefanpenner** [comment]
looks good. I'll make noise if I discover something else, thanks guys!

**Comment by stefanpenner** [comment]
This actually hasn't been solved yet.

https://github.com/tildeio/conductor.js/blob/master/dist/conductor-0.3.0.js will still fail if used with `requirejs` as the [synchronous require](https://github.com/tildeio/conductor.js/blob/master/dist/conductor-0.3.0.js#L5483)'s are not compatible with require. (They must occur on nextTick)

**Comment by hjdivad** [comment]
@stefanpenner asynchronous require will make the drop-in browser version screwy.  It should be possible to use the amd version if using requirejs, which seems appropriate anyway, no?

The thing that's inconvenient is the need to copy the footer somewhere.  What do you think about having a `'conductor/main'` or `'conductor/autostart'` module that can be used as a dependency to autostart?
